plugins {
	id 'com.unascribed.nilgradle' version '1.4.7'
}

java {
	// You can change this to be higher if you like. NilLoader itself is compiled
	// for Java 8 for compatibility with older versions.
	toolchain {
		languageVersion = JavaLanguageVersion.of(8)
	}
}

group = 'de.femtopedia'
version = '1.0'

base {
	archivesName = 'Nil125Fix'
}

repositories {
	mavenCentral()
	maven {
		url = 'https://repo.sleeping.town'
		content {
			includeGroup 'com.unascribed'
		}
	}
	maven {
		url = 'https://maven.minecraftforge.net'
		metadataSources {
			artifact()
		}
		content {
			includeGroup 'net.minecraftforge'
		}
	}
	flatDir {
		dirs 'libs'
		content {
			includeGroup 'libs'
		}
	}
}

nil {
	id "nil125fix"
	// Set this to false for a smaller JAR that can't be run as a standalone Java agent
	standalone false
}

dependencies {
	loader 'com.unascribed:nilloader:1.3.6'

	compileOnly('org.lwjgl.lwjgl:lwjgl:2.9.3') {
		transitive = false
	}

	game nil.minecraft('1.2.5', 'client')

	mod 'net.minecraftforge:forge:1.2.5-3.4.9.171:client@zip'
	mod 'libs:NotEnoughItems-Client 1.3.0.1'

	implementation 'net.fabricmc:mapping-io:0.7.1'
	compileOnly 'com.google.code.gson:gson:2.13.1'
}

mappings {
	work nil.mcpArchive('1.2.5', '62')
}
